module Constants
    CATEGORIES = [
        "Miscellaneous",
        "Ammo",
        "Arrows",
        "Bolts",
        "Construction materials",
        "Construction projects",
        "Cooking ingredients",
        "Costumes",
        "Crafting materials",
        "Familiars",
        "Farming produce",
        "Fletching materials",
        "Food and drink",
        "Herblore materials",
        "Hunting equipment",
        "Hunting produce",
        "Jewellery",
        "Mage armour",
        "Mage weapons",
        "Melee armour - low level",
        "Melee armour - mid level",
        "Melee armour - high level",
        "Melee weapons - low level",
        "Melee weapons - mid level",
        "Melee weapons - high level",
        "Mining and smithing",
        "Potions",
        "Prayer armour",
        "Prayer materials",
        "Range armour",
        "Range weapons",
        "Runecrafting",
        "Runes, Spells and Teleports",
        "Seeds",
        "Summoning scrolls",
        "Tools and containers",
        "Woodcutting product",
        "Pocket items"
    ]
end